-- Queries 

-- Query 1
SELECT MIN(weight) as Weight FROM ITEMS;
SELECT DISTINCT(DES) FROM ITEMS WHERE WEIGHT = ( SELECT MIN(weight) as Weight FROM ITEMS );

-- Query 2
SELECT * FROM WAREHOUSES WHERE LOCATION = 'Pune';

-- Query 3
SELECT C.CNAME , I.DES , O.ONO , I.ITEMNO FROM CUSTOMER C INNER JOIN ORDERS O ON O.CNO = C.CNO
INNER JOIN ORDERED_QUANTITY OQ ON O.ONO = OQ.ONO
INNER JOIN ITEMS I ON OQ.ITEMNO = I.ITEMNO
WHERE CNAME = 'Naveen';

-- Query 4
SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID;
SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB ;
SELECT WID , COUNT(SID) FROM STORES GROUP BY WID HAVING COUNT(SID) = (SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB );

SELECT WNAME FROM WAREHOUSES WHERE WID = (SELECT WID FROM STORES GROUP BY WID HAVING COUNT(SID) = (SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB ) );

-- Query 5
SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO;
SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO )SUB; 
SELECT ITEMNO , COUNT(ONO) FROM ORDERED_QUANTITY GROUP BY ITEMNO HAVING COUNT(ONO) = (SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO )SUB);

SELECT DES FROM ITEMS WHERE ITEMNO = ( SELECT ITEMNO FROM ORDERED_QUANTITY GROUP BY ITEMNO HAVING COUNT(ONO) = (SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO ) SUB) );

-- Query 6
SELECT CNAME , COUNT(ONO) TOTAL_COUNT FROM CUSTOMER C INNER JOIN ORDERS O ON C.CNO = O.CNO GROUP BY C.CNAME ORDER BY TOTAL_COUNT DESC;
   

